name: Daily Whale Tracker

on:
  schedule:
    - cron: '0 12 * * *'  # Runs daily at 12:00 UTC
  workflow_dispatch:

jobs:
  run-whale-tracker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas

      - name: Run whale tracker script
        run: python whale_tracker.py

      - name: Configure Git and disable GPG
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git config --global commit.gpgsign false

      - name: Stash uncommitted changes
        run: |
          git status
          git stash

      - name: Commit updated whales.json
        run: |
          git pull origin main --rebase
          git stash pop || true
          git add public/whales.json
          git diff --cached --quiet && echo "No changes
