name: Update Whales Hourly
on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:

jobs:
  update-whales:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install yfinance pandas

      - name: Run whale tracker
        run: python whale_tracker.py

      - name: Configure Git
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Pull latest changes to avoid non-fast-forward error
        run: git pull origin main --rebase

      - name: Commit and push if changed
        run: |
          git add public/whales.json
          git diff --quiet && echo "No changes to commit" || git commit -m "Update whales.json"
          git push origin main
