name: Update Sharks Hourly

on:
  schedule:
    - cron: '5 * * * *'  # Runs at 5 minutes past every hour
  workflow_dispatch:

jobs:
  update-sharks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pandas

      - name: Run shark tracker
        run: python sharks_tracker.py

      - name: Configure Git
        run: |
          git config --global user.name "whalewatch-bot"
          git config --global user.email "actions@github.com"

      - name: Commit and push updated sharks.json
        run: |
          git add public/sharks.json
          git commit -m "🦈 Update sharks.json (hourly sync)" || echo "No changes to commit"
          git pull origin main --rebase || echo "No remote changes to rebase"
          git push origin main
