name: Update Sharks Hourly
on:
  schedule:
    - cron: '5 * * * *'  # Every hour, staggered
  workflow_dispatch:

jobs:
  update-sharks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install pandas

      - name: Run shark tracker
        run: python sharks_tracker.py

      - name: Configure Git
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Commit and push if changed
        run: |
          git add public/sharks.json
          git diff --quiet && echo "No changes to commit" || git commit -m "Update sharks.json"
          git push origin main
